### ISSUE TITLE
Error during installation minc_1_rw.h file missing

### ISSUE THREAD

**Issue by zhengchencai** [BIC-MNI/pyezminc#4]
Hello,

It seems there is this file "minc_1_rw.h" missing in the repo. Then I got this error while installing. Could you pleae take a look? Thanks

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
minc/pyezminc.cpp:633:10: fatal error: minc_1_rw.h: No such file or directory
  633 | #include "minc_1_rw.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by gdevenyi** [comment]
Please provide the exact commands you are using, and confirm you have installed the dependencies of this software (minc-toolkit-v2)

**Comment by zhengchencai** [comment]
Thanks. I first gitclone this repo and did ```python setup.py install```. Yes, I have installed minc-toolkit-v2 and was using it previously.

**Comment by gdevenyi** [comment]
Can you please provide the complete command and output.

**Comment by zhengchencai** [comment]
Sure, 
```
❯ python setup.py install
running install
running bdist_egg
running egg_info
writing pyezminc.egg-info/PKG-INFO
writing dependency_links to pyezminc.egg-info/dependency_links.txt
writing requirements to pyezminc.egg-info/requires.txt
writing top-level names to pyezminc.egg-info/top_level.txt
file minc.py (for module minc) not found
reading manifest file 'pyezminc.egg-info/SOURCES.txt'
writing manifest file 'pyezminc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file minc.py (for module minc) not found
file minc.py (for module minc) not found
running build_ext
skipping 'minc/pyezminc.cpp' Cython extension (up-to-date)
building 'minc.pyezminc' extension
gcc -pthread -B /home/zcai/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/minc/1.9.15/include -I/home/zcai/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/zcai/anaconda3/include/python3.8 -c minc/pyezminc.cpp -o build/temp.linux-x86_64-3.8/minc/pyezminc.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
minc/pyezminc.cpp:633:10: fatal error: minc_1_rw.h: No such file or directory
  633 | #include "minc_1_rw.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by hazedine** [comment]
Hi, `/opt/minc/1.9.15` is the default path used by the setup.py according to https://github.com/BIC-MNI/pyezminc/blob/4a1c16f834f1bbe4ebbef2985f42dac1ebd30dd2/setup.py#L32

@zhengchencai could you please confirm that `/opt/minc/1.9.15/include/minc_1_rw.h` exists on your system? If not, please make sure the environment variable `MINC_TOOLKIT` is defined in the terminal you are using for compiling pyezminc?

**Comment by gdevenyi** [comment]
`minc_1_rw.h` is part of the includes of minc-toolkit-v2. Your build environment is not properly setup with your minc-toolkit-v2 install. Typically this is done by `source /path/to/your/minc-toolkit-v2/install/minc-toolkit-config.sh`, which exports the $MINC_TOOLKIT environment variable, which the build uses to setup proper includes.

**Comment by vfonov** [comment]
Based on the fact that this is all inside anaconda, I would say just do 
`conda install -c vfonov pyezminc`

**Comment by zhengchencai** [comment]
Sorry for the late reply. ```conda install -c vfonov pyezminc``` worked. @gdevenyi sorry I was silly and didn't notice I was actually using the minctool from freesurfer... so apparently, I just installed minctook but did not export the path. Now I can use pyezminc :)

**Comment by gdevenyi** [comment]
@zhengchencai beware that the minc tools inside freesurfer are very old and forked from a long time ago :+1:

**Comment by zhengchencai** [comment]
Yes, I noticed that and removed it. Now I am using the latest version. Thanks a lot.
